name: Build and Push Container

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          CURRENT_BRANCH=$VERSION
          VERSION="${VERSION}-$(git rev-parse --short ${{ github.sha }})"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag ${{ github.event.repository.name }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          echo "current branch: $CURRENT_BRANCH"
          echo "default branch: ${{ github.event.repository.default_branch }}"

          if [ "$CURRENT_BRANCH" = "${{ github.event.repository.default_branch }}" ]; then
            echo "push latest"
            docker tag ${{ github.event.repository.name }} $IMAGE_ID:latest
            docker push $IMAGE_ID:latest
          fi
