name: Build and Push Container

on:
  push:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ REGISTRY }}
          username: ${{ github.actor }}
          passowrd: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=sha,prefix={{branch}}-

      - name: build and push Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
